import {
  Activity,
  AlarmClock,
  Apple,
  Award,
  Baby,
  BadgeCheck,
  Bed,
  Bell,
  BookHeart,
  BookOpen,
  Brain,
  BriefcaseMedical,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Compass,
  Dumbbell,
  FileHeart,
  FileText,
  Flame,
  Flower2,
  Footprints,
  Gem,
  HandHeart,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  Home,
  Hospital,
  Info,
  KeyRound,
  Languages,
  Leaf,
  LibraryBig,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquareHeart,
  MessagesSquare,
  Moon,
  Network,
  NotebookPen,
  Palette,
  Phone,
  PhoneCall,
  PiggyBank,
  Puzzle,
  Quote,
  Scale,
  ScrollText,
  ShieldCheck,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Sunrise,
  Target,
  Telescope,
  ThumbsUp,
  TreeDeciduous,
  Trophy,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  Waves,
  Wind,
  type LucideIcon,
} from "lucide-react";

/**
 * Whitelist of icons the dashboard can attach to content.
 *
 * Keeping an explicit registry (instead of importing the whole lucide set
 * dynamically) means the client bundle only carries what we actually use, and
 * a typo in the dashboard can never crash a page.
 */
export const ICON_REGISTRY = {
  Activity,
  AlarmClock,
  Apple,
  Award,
  Baby,
  BadgeCheck,
  Bed,
  Bell,
  BookHeart,
  BookOpen,
  Brain,
  BriefcaseMedical,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Compass,
  Dumbbell,
  FileHeart,
  FileText,
  Flame,
  Flower2,
  Footprints,
  Gem,
  HandHeart,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  Home,
  Hospital,
  Info,
  KeyRound,
  Languages,
  Leaf,
  LibraryBig,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquareHeart,
  MessagesSquare,
  Moon,
  Network,
  NotebookPen,
  Palette,
  Phone,
  PhoneCall,
  PiggyBank,
  Puzzle,
  Quote,
  Scale,
  ScrollText,
  ShieldCheck,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Sunrise,
  Target,
  Telescope,
  ThumbsUp,
  TreeDeciduous,
  Trophy,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  Waves,
  Wind,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICON_REGISTRY;

/** Options shown in the dashboard's icon picker. */
export const ICON_CHOICES: Array<{ name: IconName; label: string }> = (
  [
    "HeartHandshake",
    "HeartPulse",
    "Heart",
    "ShieldCheck",
    "BadgeCheck",
    "Brain",
    "Users",
    "UsersRound",
    "UserRound",
    "Handshake",
    "HandHeart",
    "MessageSquareHeart",
    "MessageCircle",
    "MessagesSquare",
    "BookHeart",
    "BookOpen",
    "Sprout",
    "Leaf",
    "TreeDeciduous",
    "Flower2",
    "Sunrise",
    "Sun",
    "Moon",
    "Star",
    "Trophy",
    "Award",
    "Gem",
    "Target",
    "Compass",
    "Sparkles",
    "Lightbulb",
    "Lamp",
    "Activity",
    "Waves",
    "Wind",
    "Flame",
    "Footprints",
    "Dumbbell",
    "Palette",
    "Music",
    "Drama",
    "NotebookPen",
    "ScrollText",
    "FileHeart",
    "FileText",
    "ClipboardCheck",
    "ClipboardList",
    "Stethoscope",
    "Hospital",
    "BriefcaseMedical",
    "Headphones",
    "Puzzle",
    "Network",
    "Scale",
    "LibraryBig",
    "Telescope",
    "ThumbsUp",
    "Quote",
    "CalendarCheck",
    "AlarmClock",
    "Clock",
    "Baby",
    "Home",
    "Building2",
    "Lock",
    "KeyRound",
    "Languages",
    "Apple",
    "Bed",
    "PiggyBank",
    "Wallet",
    "Info",
    "CircleHelp",
  ] as IconName[]
)
  .filter((name) => Boolean(ICON_REGISTRY[name]))
  .map((name) => ({
    name,
    label: ICON_REGISTRY[name]?.displayName ?? name,
  }));

const FALLBACK: LucideIcon = Sparkles;

export function getIcon(name?: string | null): LucideIcon {
  if (!name) return FALLBACK;
  return ICON_REGISTRY[name as IconName] ?? FALLBACK;
}

export type { LucideIcon };
